steps:
  # Step 1: Build the app image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/text-learn-app", "."]
    dir: "app"

  # Step 2: Build the db image
  - name: "gcr.io/cloud-builders/docker"
    args: ["pull", "postgres"]

  # Step 3: Build the pgweb image
  - name: "gcr.io/cloud-builders/docker"
    args: ["pull", "sosedoff/pgweb"]

  # Step 4: Push the app image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/text-learn-app"]

  # Step 5: Push the db image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "postgres", "gcr.io/$PROJECT_ID/postgres"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/postgres"]

  # Step 6: Push the pgweb image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "sosedoff/pgweb", "gcr.io/$PROJECT_ID/pgweb"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/pgweb"]

images:
  - "gcr.io/$PROJECT_ID/text-learn-app"
  - "gcr.io/$PROJECT_ID/postgres"
  - "gcr.io/$PROJECT_ID/pgweb"

options:
  logging: CLOUD_LOGGING_ONLY
