services:
  app:
    image: text-learn-app
    build: .
    ports:
      - "8080:8080" # Map port 8080 of the host to port 8080 of the container
    depends_on: # Wait for the database to be ready before starting the app
      - db
    volumes:
      - text-learn-uploads:/usr/src/app/uploads
  db:
    image: postgres
    environment:
      POSTGRES_DB: text-learn
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432" # Expose PostgreSQL port internally
    volumes:
      - text-learn-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgweb:
    image: sosedoff/pgweb
    environment:
      PGW_DB_HOST: db
      PGW_DB_USER: admin
      PGW_DB_PASS: pass123
      PGW_DB_NAME: text-learn
    ports:
      - "8081:8081" # Expose pgweb port internally
    depends_on: # Wait for the database to be ready before starting the app
      - db

volumes:
  text-learn-db:
  text-learn-uploads:
